In [2]:
a = "Ali"
print(a)

Ali


In [3]:
a = "wire"
b= "pen"
c="headphone"
d= "tissue"

In [ ]:
# array 

In [5]:
import numpy as np

a = np.array([1,2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
import numpy as np

a = np.arrange(6)
a2 = a[np.newaxis, :]
a2.shape

In [7]:
import numpy as np
#one dimensional
a = np.array([5,5,5,])
a

array([5, 5, 5])

In [8]:
type(a)

numpy.ndarray

In [9]:
#list of lists
#two dimensional
b = np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
import numpy as np
a = np.array([1,2,4,5,3])
a

array([1, 2, 4, 5, 3])

In [12]:
b = np.zeros(2)
b

array([0., 0.])

In [13]:
c = np.ones(3)
c

array([1., 1., 1.])

In [14]:
# create an empty array with 2 elements
d = np.empty(3)
d

array([1., 1., 1.])

In [20]:
#  with range of elements
e = np.arange(6) # 6 include nahi hota aur 0 sa start hota hai python main
e

array([0, 1, 2, 3, 4, 5])

In [16]:
# with specific range of elements
f = np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
# continue
g = np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# linearly spaced arrays
h = np.linspace(0,10, num=5) #gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
# linearly spaced arrays
h = np.linspace(0,10, num=6) #gives use 5 nums
h

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [22]:
# specific data types in array
i = np.ones(5, dtype = np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [24]:
j = np.ones(3, dtype = np.float64)
j

array([1., 1., 1.])

### 2 D Array 

In [27]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
np.empty([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 3 D Array

In [31]:
# makind and reshaping a 3D array
c = np.arange(24). reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

###  Numpy practice session

In [ ]:
#import library in jupyter notebook
import numpy as np



 ### Creating an array

In [32]:
# I-D array
food =np.array(["Pakora","Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [33]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [34]:
type(price)

numpy.ndarray

In [35]:
type(food)

numpy.ndarray

In [36]:
len(price)

3

In [37]:
len(food)

3

In [39]:
price[2]

5

In [40]:
price[0:]

array([5, 5, 5])

In [43]:
food[1]

'Samosa'

In [44]:
price.mean()

5.0

In [45]:
# zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [46]:
# one methods
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
# empty mehtod
np.empty(5)

array([1., 1., 1., 1., 1.])

In [49]:
#range method
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# range method
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [51]:
# range method
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
# table
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [53]:
# line space
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
# line space
np.linspace(10,100,num=10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [59]:
# specify data type
np.ones(50, dtype =np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [60]:
np.ones(50, dtype =np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

###  Array Functions

In [62]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [63]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [64]:
b =  np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [67]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [68]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

###  2-D Arrays

In [70]:
a = np.array([[1,2,4,5,3],[5,4,3,2,1]])
a

array([[1, 2, 4, 5, 3],
       [5, 4, 3, 2, 1]])

In [74]:
b = np.array([[6,7,8,8,9], [8,9,4,3,2]])
b

array([[6, 7, 8, 8, 9],
       [8, 9, 4, 3, 2]])

In [77]:
c = np.concatenate((a,b))
c

array([[1, 2, 4, 5, 3],
       [5, 4, 3, 2, 1],
       [6, 7, 8, 8, 9],
       [8, 9, 4, 3, 2]])

In [79]:
c = np.concatenate((a,b), axis = 1)
c

array([[1, 2, 4, 5, 3, 6, 7, 8, 8, 9],
       [5, 4, 3, 2, 1, 8, 9, 4, 3, 2]])

In [80]:
c = np.concatenate((a,b), axis = 0)
c

array([[1, 2, 4, 5, 3],
       [5, 4, 3, 2, 1],
       [6, 7, 8, 8, 9],
       [8, 9, 4, 3, 2]])

In [81]:
a = np.array ([[[0,1,2,3], [4,5,6,7]],
             [[1,2,3,4],[5,6,7,8]],
             [[2,3,4,5],[9,8,7,6]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[2, 3, 4, 5],
        [9, 8, 7, 6]]])

In [83]:
# to find the number of dimension
a.ndim

3

In [86]:
type(a)

numpy.ndarray

In [84]:
b = np.array([[5,6,7],
             [8,9,10],
              [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [85]:
b.ndim

2

In [89]:
# number of elements
a.size

24

In [88]:
b.size

9

In [91]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[2, 3, 4, 5],
        [9, 8, 7, 6]]])

In [90]:
# shape
a.shape

(3, 2, 4)

In [92]:
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [93]:
b.shape

(3, 3)

In [98]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
# reshape
a.shape

(7,)

In [99]:
a.reshape

<function ndarray.reshape>

In [100]:
b.shape

(3, 3)

In [101]:
b = a.reshape(3,3) # 3*3 = 9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
#reshape
np.reshape(a, newshape = (1,9), order ="C")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [103]:
# conver 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
a.shape

(9,)

In [106]:
#row wise 
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [107]:
b.shape

(1, 9)

In [109]:
# column wise
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [110]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [113]:
# multiplication
a *6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [114]:
a +6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [115]:
a.sum()

45

In [116]:
a.mean()

5.0

In [117]:
a.std()

2.581988897471611

In [118]:
a.min()

1

In [119]:
a.max()

9